# Generated by Django 4.1.1 on 2022-09-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='number',
            field=models.IntegerField(),
        ),
    ]
