# Generated by Django 4.1.1 on 2022-09-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_resource_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='name',
            field=models.CharField(default='Wood', max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='number',
            field=models.IntegerField(default=800),
        ),
        migrations.AlterField(
            model_name='resource',
            name='production',
            field=models.IntegerField(default=10),
        ),
    ]
