# Generated by Django 4.1.1 on 2022-09-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_resource_name_alter_resource_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='negative',
            field=models.BooleanField(default=False),
        ),
    ]
